import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

// import css 
import "./styles/globals.css";

import { ToastContainer } from "react-toastify";
import TopLoader from "./components/TopLoader";
import { ReduxProvider } from "../lib/store/ReduxProvider";
import Storeuser from "./components/StoreUser";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Nuna | Social Media",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <TopLoader />
        <ReduxProvider>
          <Storeuser />
          {children}
        </ReduxProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
